spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.producter.key-serizalizer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producter.value-serizalizer: org.apache.kafka.common.serialization.StringSerializer